config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments

  resources :posts

  root to: 'visitors#index'
  devise_for :users
  resources :users
  
  match 'like' => 'users#like', :via => [:post]
  match 'unlike' => 'users#unlike', :via => [:post]
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ActiveRecord::Base
    default_scope -> { order(created_at: :desc) }
    belongs_to :user
    validates :content, presence: true, length: { maximum: 300 }
    has_many :post_attachments
    accepts_nested_attributes_for :post_attachments
    acts_as_likeable
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
   mount_uploader :picture, PictureUploader
   belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  acts_as_liker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @post_attachments = PostAttachment.all
    respond_with(@post_attachments)
  end

  def show
    respond_with(@post_attachment)
  end

  def new
    @post_attachment = PostAttachment.new
    respond_with(@post_attachment)
  end

  def edit
  end

  def create
    @post_attachment = PostAttachment.new(post_attachment_params)
    @post_attachment.save
    respond_with(@post_attachment)
  end

  def update
    @post_attachment.update(post_attachment_params)
    respond_with(@post_attachment)
  end

  def destroy
    @post_attachment.destroy
    respond_with(@post_attachment)
  end

  private
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :picture)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :new, :edit, :destroy]

  respond_to :html

  def index

    unless user_signed_in?
        redirect_to new_user_session_path
    else
        @post = Post.new 
        @posts = Post.all
        @user = User.all
        
    respond_with(@posts)
    end
  end

  def show
   @post = Post.find(params[:id])
   @post_attachments = @post.post_attachments.all
  end

  def new
    @post = Post.new
    respond_with(@post)
    @post_attachment = @post.post_attachments.build
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
       if @post.save 
         
         params[:post_attachments]['picture'].each do |a|
            @post_attachment = @post.post_attachments.create!(:picture => a, :post_id => @post.id)
         end
         format.html { redirect_to @post, notice: 'Post was successfully created.' }
       else
         format.html { render action: 'new' }
         render 'new'
       end
    end
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:user_id, :title, :content, post_attachments_attributes: [:id, :post_id, :picture])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!


  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  def like
      if params[:likeable_type] == "Post"
          @likeable = Post.find(params[:likeable_id])
      else
          @likeable = Comment.find(params[:likeable_id])
      end
	  current_user.like!(@likeable)
  	respond_to do |format|
        format.json { render json: { likes: @likeable.likers(User).count } }
    end
  end
  
  def unlike
      if params[:likeable_type] == "Post"
          @likeable = Post.find(params[:likeable_id])
      else
          @likeable = Comment.find(params[:likeable_id])
      end
  	current_user.unlike!(@likeable)
	  respond_to do |format|
        format.json { render json: { likes: @likeable.likers(User).count } }
    end
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    unless user_signed_in?
        redirect_to new_user_session_path
    else
        @post = Post.new 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Posts', posts_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
 
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/post_attachments/_form.html.erb
<%= simple_form_for(@post_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :post_id %>
    <%= f.input :picture %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<h1>Listing post_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.picture %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @post_attachment.picture %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
   <div class="form-inputs">
     <%= f.label :title %><br>
     <%= f.text_field :title %>
     <%= f.label :content %><br>
     <%= f.text_area :content %>
   </div>

<%= f.file_field :picture, :multiple => true, name: "post_attachments[picture][]" %>
   
<%= f.fields_for :post_attachments do |p| %>
     <div class="form-inputs">
       <%= p.label :picture %><br>
       <%= p.file_field :picture, :multiple => true, name: "post_attachments[picture][]" %>
     </div>
<% end %>

   <div class="form-actions">
     <%= f.submit %>
   </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>


<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user.admin? or post.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', @post, remote: true, method: :delete %></td>
        <% end %>
   
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>

</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= @post.content %>



<% @post_attachments.each do |p| %>
     <div class="thumbnail">
         <%= image_tag p.picture_url, :style => "width: 500px"; %>
     </div>
<% end %>








<% if user_signed_in? %>
<%= render 'shared/like', likeable: @post  %> 
<%= render 'shared/unlike', likeable: @post %>
<% end %>

<div class="likes"><%= pluralize(@post.likers(User).count, 'like')%></div>
<div id="likeCounts"><%= @post.likers(User).count %></div> <p>likes</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_like.html.erb
<% if current_user.likes?(likeable) %>
	<div id="like", class="hide">
	    <%= link_to "like", like_path(likeable_id: likeable.id, likeable_type: likeable.class) , remote: true, method: :post %>
	</div>
<% else %>
	<div id="like">
	    <%= link_to "like", like_path(likeable_id: likeable.id, likeable_type: likeable.class) , remote: true, method: :post %>
	</div>
<% end %>

app/views/shared/_like_form.html.erb
<% if user_signed_in? %>

		<div id="like_form">
			<% if current_user.likes?(likeable) %>
				<%= render 'shared/unlike', likeable: likeable %>
			<% else %>
				<%= render 'shared/like', likeable: likeable  %>
			<% end %>
	</div>
<% end %>

app/views/shared/_unlike.html.erb
<% if current_user.likes?(likeable) %>
	<div id="unlike">
	    <%= link_to "Unlike", unlike_path(likeable_id: likeable.id, likeable_type: likeable.class ), remote: true, method: :post %>
	</div>
<% else %>
	<div id="unlike", class="hide">
	    <%= link_to "Unlike", unlike_path(likeable_id: likeable.id, likeable_type: likeable.class ), remote: true, method: :post %>
	</div>
<% end %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<%= render 'posts/form' %>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>